In [4]:
import numpy as np 

In [5]:
arr1 = np.array([28,46,75,75])

In [6]:
arr1

array([28, 46, 75, 75])

In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


In [8]:
arr1.reshape(2,2)

array([[28, 46],
       [75, 75]])

In [12]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#idenitity matrix


In [21]:
##Numpy vectorisation operation 
arr = np.array([23,4,64,4,45,44])
arr2 = np.array([10,11,12,13,34,54])
print("Addition:-",arr+arr2)
print("Multiplication:-",arr*arr2)
print("Substraction:-",arr-arr2)
print("Moduless:-",arr%arr2)

Addition:- [33 15 76 17 79 98]
Multiplication:- [ 230   44  768   52 1530 2376]
Substraction:- [ 13  -7  52  -9  11 -10]
Moduless:- [ 3  4  4  4 11 44]


In [23]:
np.sqrt(arr1)

array([5.29150262, 6.78232998, 8.66025404, 8.66025404])

In [25]:
np.exp(arr1)

array([1.44625706e+12, 9.49611942e+19, 3.73324200e+32, 3.73324200e+32])

In [27]:
np.sin(arr)

array([-0.8462204 , -0.7568025 ,  0.92002604, -0.7568025 ,  0.85090352,
        0.01770193])

In [29]:
np.log(arr)

array([3.13549422, 1.38629436, 4.15888308, 1.38629436, 3.80666249,
       3.78418963])

In [35]:
#Array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [36]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
arr[0][0]

np.int64(1)